### ISSUE TITLE
ext2rd.cpp:5:10: fatal error: 'map' file not found

### ISSUE THREAD

**Issue by lleevveell66** [nlitsme/extfstools#1]
[root@lie-recovery extfstools]# make
clang++ -g -Wall -c -O3 -I itslib -D_UNIX -D_NO_RAPI -I /usr/local/include -I . -std=c++11 -stdlib=libc++  -MD ext2rd.cpp -o ext2rd.o
ext2rd.cpp:5:10: fatal error: 'map' file not found
#include <map>
         ^
1 error generated.
make: *** [ext2rd.o] Error 1
[root@lie-recovery extfstools]#

Where is that from?   A required package?

**Comment by nlitsme** [comment]
'map'  is from the c++ standard  STL library.  it should normally be installed with your c++ compiler.  for clang it is called  [libc++](https://libcxx.llvm.org/)
