### ISSUE TITLE
build faield

### ISSUE THREAD

**Issue by weijen6** [nlitsme/extfstools#10]
vcpkg install vcpkg install boost:x64-windows

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Linux\GNU MCU Eclipse\Build Tools\2.9-20170629-1013\bin\make" vc
"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" -G"Visual Studio 16 2019" -B build .
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29336.0
-- The CXX compiler identification is MSVC 19.28.29336.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR date_time)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  CMakeLists.txt:43 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/extfstools-master/build/CMakeFiles/CMakeOutput.log".
Makefile:7: recipe for target 'vc' failed
make: *** [vc] Error 1

**Comment by nlitsme** [comment]
one thing you can do:  set an environment variable 'BOOST_ROOT' with the path of your boost directory.

Alternatively, my latest update will automatically download a temporary copy of the boost libraries ( about a 120M byte download )  and use that.

**Comment by weijen6** [comment]
Thanks for your help. 
Program can be built.
ext2rd.exe is OK.
But an error occurs when running ext2dump.exe 
![image](https://user-images.githubusercontent.com/32688959/106505359-2aa9a400-6503-11eb-8925-a3006b292143.png)

**Comment by nlitsme** [comment]
I updated ext2dump to give you a better error message.  This happens when you don't pass an argument
