### ISSUE TITLE
ext2rd.cpp:5:10: fatal error: 'map' file not found

### ISSUE THREAD

**Issue by rigortek** [nlitsme/extfstools#2]
clang++ -g -Wall -c -O3 -I itslib -D_UNIX -D_NO_RAPI -I /usr/local/include -I . -std=c++11 -stdlib=libc++  -MD ext2rd.cpp -o ext2rd.o 
ext2rd.cpp:5:10: fatal error: 'map' file not found
#include <map>
         ^
1 error generated.
make: *** [ext2rd.o] Error 1

**Comment by nlitsme** [comment]
I think your compiler may have some missing parts,  'map'  is part of the c++ standard library.
