### ISSUE TITLE
When using ext2rd on a not yet existing output directory it fails with a "No such file or directory" error

### ISSUE THREAD

**Issue by jaapcrezee** [nlitsme/extfstools#8]
The error message it quite fuzzy:

```
mkdir(savepath): No such file or directory
mkdir(savepath): No such file or directory
mkdir(savepath): No such file or directory
mkdir(savepath): No such file or directory
mkdir(savepath): No such file or directory
mkdir(savepath): No such file or directory
EXCEPTION - did you specify -B for a block device?
```

If you create the directory before running ext2rd it works okay.

Expected behaviour: ext2rd should create the directory if it does not exist or give a clear message that the output directory should be created before using the tool.

**Comment by nlitsme** [comment]
I improved the mkdir handling in https://github.com/nlitsme/extfstools/commit/aa9d9b1acb3c1eb030bee33d009a9833c62ff5c7

does this solve your problem?

**Comment by jaapcrezee** [comment]
Excellent! Now it works without creating the directory. Dank u.
