### ISSUE TITLE
gcc version compatibility

### ISSUE THREAD

**Issue by copslock** [nlitsme/extfstools#9]
Dear author,the current code needs C++17,which means at least gcc(7.1+)/ubuntu 18.04+,the gcc upgrade is complex in lower version systems

**Comment by nlitsme** [comment]
I changed my code to work with c++11.
Also I changed my build system to use cmake.
Currently builds work on: linux, macos, freebsd and windows.

**Comment by copslock** [comment]
> I changed my code to work with c++11.
> Also I changed my build system to use cmake.
> Currently builds work on: linux, macos, freebsd and windows.

Thanks a lot ,lower target version gives better compalibility
